[CORE] Unpublish artefacts
eclipse/dirigible pull request #1338
Opened 2021-12-09 15:35 UTC by cheezus1

### What does this PR do?
Adds PublisherHandler abstraction, which is to be implemented for every artefact synchronizer.

Adds OData PublisherHandler implementation.

2021-12-15 15:31 UTC, ThuF requested changes
Few minor comments to be addressed, before merging the PR

2021-12-15 15:31 UTC, ThuF commented on modules/core/core-publisher/src/main/java/org/eclipse/dirigible/core/publisher/api/PublisherHandler.java
> +public abstract class PublisherHandler {
Create `IPublishHandler` interface to extract the abstract methods there:

```java
public abstract class PublisherHandler {
```

->

```java
public abstract class AbstractPublishHandler implements IPublishHandler {
```

2021-12-15 15:31 UTC, ThuF commented on modules/core/core-publisher/src/main/java/org/eclipse/dirigible/core/publisher/api/PublisherHandler.java
> +    public abstract void afterUnpublish(String location) throws SchedulerException;
Extract into `IPublishHandler` interface

2021-12-15 15:31 UTC, ThuF commented on modules/engines/engine-odata/src/main/resources/META-INF/services/org.eclipse.dirigible.core.publisher.api.PublisherHandler
> +org.eclipse.dirigible.engine.odata2.synchronizer.ODataSynchronizerPublisherHandler	# OData Synchronizer Publisher Handler
Change the file name to point to the`IPublishHandler` interface:


`org.eclipse.dirigible.core.publisher.api.PublisherHandler `

->

`org.eclipse.dirigible.core.publisher.api.IPublishHandler`

2021-12-15 15:31 UTC, ThuF commented on modules/core/core-publisher/src/main/java/org/eclipse/dirigible/core/publisher/api/PublisherHandler.java
> +    protected String getLocationQueryParam(String location, boolean includeLeadingSeparator) {
Change the method visibility from `protected` to `private`

2021-12-15 15:31 UTC, ThuF commented on modules/core/core-publisher/src/main/java/org/eclipse/dirigible/core/publisher/api/PublisherHandler.java
> +    }
Change the method in the following way:
```java
    protected void removeMetadata(PersistenceManager persistenceManager, String table, String column, String location, boolean includeLeadingSeparator) throws SchedulerException {
        try (Connection connection = dataSource.getConnection()) {
            SqlFactory sqlFactory = SqlFactory.getNative(connection);

            if (sqlFactory.exists(connection, table)) {
                String sql = sqlFactory.delete().from(table).where(new StringBuilder().append(column).append(" LIKE ?").toString()).build();
                String locationQueryParam = getLocationQueryParam(location, includeLeadingSeparator);
                persistenceManager.execute(connection, sql, locationQueryParam);
            }
        } catch (SQLException e) {
            throw new SchedulerException(e);
        }
    }
```

2021-12-15 15:31 UTC, ThuF commented on modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/synchronizer/ODataSynchronizerPublisherHandler.java
> +        removeMetadata(new PersistenceManager<ODataSchemaDefinition>(), "DIRIGIBLE_ODATA_SCHEMA", "ODATAX_LOCATION", locationQueryParam);
Update to:
```java
removeMetadata(new PersistenceManager<ODataDefinition>(), "DIRIGIBLE_ODATA", "ODATA_LOCATION", location, true);
removeMetadata(new PersistenceManager<ODataContainerDefinition>(), "DIRIGIBLE_ODATA_CONTAINER", "ODATAC_LOCATION", location, true);
removeMetadata(new PersistenceManager<ODataHandlerDefinition>(), "DIRIGIBLE_ODATA_HANDLER", "ODATAH_LOCATION", location, true);
removeMetadata(new PersistenceManager<ODataMappingDefinition>(), "DIRIGIBLE_ODATA_MAPPING", "ODATAM_LOCATION", location, true);
removeMetadata(new PersistenceManager<ODataSchemaDefinition>(), "DIRIGIBLE_ODATA_SCHEMA", "ODATAX_LOCATION", location, true);
```

2021-12-18 08:08 UTC, delchev approved these changes

2021-12-18 08:09 UTC, merged