Configure variables for kyma and cloud foundry destination services
eclipse/dirigible pull request #1489
Opened 2022-01-28 10:01 UTC by d-velev

This PR makes it so that the environment variables needed for destination services in kyma and cloud foundry are set in dirigible with the same keys for both platforms. For kyma, the `DIRIGIBLE_OAUTH_PREFIX` and `DIRIGIBLE_DESTINATION_PREFIX` variables can be optionally set so that the service specific variables don't overlap.

2022-01-28 10:03 UTC, d-velev commented
@ThuF is there a better place for the `DIRIGIBLE_DESTINATION_` constants? There's an `OAuthService` class but no such class for the destination service.

2022-01-31 09:37 UTC, dpanayotov requested changes

2022-01-31 09:37 UTC, dpanayotov commented on releng/sap-cf-base/src/main/java/org/eclipse/dirigible/cf/utils/CloudFoundryUtils.java
> +		private List<DestinationEnv> destinationEnv;
`@SerializedName("destination")`

2022-01-31 09:37 UTC, dpanayotov commented on releng/sap-kyma-base/src/main/java/org/eclipse/dirigible/kyma/KymaModule.java
> +		String destinationPrefix = Configuration.get(DIRIGIBLE_DESTINATION_PREFIX, "");
the default should be `destination_`, no?

2022-01-31 10:18 UTC, dpanayotov approved these changes

2022-01-31 10:22 UTC, merged