Specific file types in WS
eclipse/dirigible pull request #1698
Opened 2022-04-08 13:53 UTC by dimitarquanterall

Signed-off-by: dimitarquanterall <d.aleksandrov@sap.com>

### What does this PR do?

Adds support for new options in extension definitions - nameless, one file of a type per folder, static name (create without editing name)

### What issues does this PR fix or reference?

https://github.com/SAP/xsk/issues/765

2022-04-08 14:16 UTC, StanZGenchev commented on pom.xml
> +	<version>7.0.0-cd </version>
This is wrong. The version here should not be edited manually.

2022-04-11 08:25 UTC, tdermendjiev approved these changes

2022-04-11 08:46 UTC, ThuF requested changes

2022-04-11 08:46 UTC, ThuF commented on ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.js
> +                                    else fileNode.text = `file.${fileTemplate.extension}`;
Please do `if-else-if-else` statements (even single lined), in the following way:
```javascript
if (fileTemplate.nameless) {
  fileNode.text = `.${fileTemplate.extension}`;
} else {
  fileNode.text = `file.${fileTemplate.extension}`;
}
```

2022-04-11 08:46 UTC, ThuF commented on ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.js
> +                                    }
The following code can be refactored as follows:
```javascript
if (fileTemplate.nameless) {
  if (nodeChildren[nc] === `.${fileTemplate.extension}`) {
    isDisabled = true;
    break;
  }
} else if (nodeChildren[nc].endsWith(`.${fileTemplate.extension}`)) {
  isDisabled = true;
  break;
}
```
&#8594;
```javascript
if (fileTemplate.nameless && nodeChildren[nc] === `.${fileTemplate.extension}` || nodeChildren[nc].endsWith(`.${fileTemplate.extension}`)) {
  isDisabled = true;
  break;
}
```

2022-04-11 08:46 UTC, ThuF commented on ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.js
> +                                    else fileNode.text = `file.${fileTemplate.extension}`;
Same about the `if-else-if-else`

2022-04-11 08:46 UTC, ThuF commented on ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.js
> +                if (type != 'zip' && type != 'x-zip') return false;
Same about `if-else-if-else`

2022-04-11 08:46 UTC, ThuF commented on ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.js
> +                                    }
Please reduce the complexity, as shown bellow.

2022-04-11 08:46 UTC, ThuF commented on ide/ui/ide-workspace/src/main/resources/META-INF/dirigible/ide-workspace/workspace.js
> +            if (priorityFileTemplates[i].isModel) models.push(priorityFileTemplates[i].extension);
Same about `if-else-if-else`

2022-04-11 08:46 UTC, ThuF commented on ide/ui/ide-documents/src/main/resources/META-INF/dirigible/ide-documents/index.html
> +                    return $http.get(requestUrl);
```javascript
return $http.get('/services/v4/js/ide-documents/api/constraints');
```

2022-04-11 13:00 UTC, StanZGenchev approved these changes

2022-04-12 08:52 UTC, ThuF approved these changes

2022-04-12 08:52 UTC, merged