OData CUD procedure handlers
eclipse/dirigible pull request #1898
Opened 2022-06-27 14:16 UTC by cheezus1

AbstractSQLProcessor now checks if there is an error document present in the context, generated during handler execution.

2022-06-28 09:10 UTC, BorisNen requested changes
Could you move the conditions to a separate method called isErrorDocumentPresent() and then use the method if(isErrorDocumentPresent()) -> return get(ERROR_DOCUMENT) for all checks below?

2022-06-28 09:10 UTC, BorisNen commented on modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java
> +            if(handlerContext.containsKey(ERROR_DOCUMENT) && handlerContext.get(ERROR_DOCUMENT) != null) {
Could you move the conditions to a separate method called isErrorDocumentPresent() and then use the method if(isErrorDocumentPresent()) -> return get(ERROR_DOCUMENT) for all checks below?

2022-06-28 10:25 UTC, BorisNen approved these changes

2022-06-28 11:25 UTC, MarinHadzhiev commented on modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java
> +            }
getting the result of executing method from input param of the method is bad. Why not just to return ODataResponse from the handler method?

2022-06-28 11:28 UTC, MarinHadzhiev requested changes
in general getting the result of method execution from an input param of the method is bad. Why not just to return ODataResponse from the handler method?

2022-06-28 11:28 UTC, MarinHadzhiev commented on modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java
> +            }
same as above comment

2022-06-28 11:28 UTC, MarinHadzhiev commented on modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java
> +                    }
same as above comment

2022-07-11 11:20 UTC, MarinHadzhiev requested changes

2022-07-11 11:20 UTC, MarinHadzhiev commented on modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java
> +                    entry = parseEntry(entitySet, entityInputStream, response.getContentHeader(), false);
Do you need this logic? Why not just return the response or ODataResponse.fromResponse(response)? And all streams must be closed.

2022-07-11 11:20 UTC, MarinHadzhiev commented on modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java
> +                    ODataResponse afterCreateEntityResponse = this.odata2EventHandler.afterCreateEntity(uriInfo, requestContentType, contentType, entry, handlerContext);
if you call afterCreateEntity here you should not call it again after the if statement bellow, actually you can't reach the code bellow

2022-07-11 11:20 UTC, MarinHadzhiev commented on modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java
> +            return EntityProvider.writeEntry(contentType, entitySet, entry.getProperties(), writeProperties);
Do you need this logic? It the same as above - copy/paste?

2022-07-20 14:43 UTC, MarinHadzhiev requested changes

2022-07-20 14:43 UTC, MarinHadzhiev commented on modules/engines/engine-odata/src/main/java/org/eclipse/dirigible/engine/odata2/handler/ScriptingOData2EventHandler.java
> +    private static final String ERROR_EXECUTING_XSJSLIB_HANDLER = "Error executing .xsjslib handler: ";
This is generic scripting handler for the dirigible, it is not only for xsjslib functions. It is also used with the standard Dirigible OData events where the handler function could be in a js file. This should be a generic message.

2022-07-20 14:43 UTC, MarinHadzhiev commented on modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java
> +                    throw new ODataException("Cannot create entity without key(s)");
add info about the entry like name or id to the exception message, it will be easier to debug it.

2022-07-20 14:43 UTC, MarinHadzhiev commented on modules/odata/odata-core/src/main/java/org/eclipse/dirigible/engine/odata2/sql/processor/AbstractSQLProcessor.java
>      }
Is it possible to put in the context - uriInfo, entry, getDataSource and ODataContext everything else could be build based on them. This way you will not need to create and add sql queries specific for the ScriptingHandler implementation and each implementation will be able to use them to implement it's logic.

Also the input stream should be closed.

2022-07-25 13:05 UTC, MarinHadzhiev approved these changes

2022-07-26 07:36 UTC, merged