[GH-#2661] Added missing setBinaryStream function
eclipse/dirigible pull request #2662
Opened 2023-08-03 08:13 UTC by nedelcho-delchev-tues

### What does this PR do?
Adds missing setBinaryStream function in DB API and updated the [documentation](https://www.dirigible.io/api/database/database/#preparedstatement).

### What issues does this PR fix or reference?
fixes #2661

2023-08-03 11:49 UTC, vmutafov requested changes

2023-08-03 11:49 UTC, vmutafov commented on components/api-database/src/main/resources/META-INF/dirigible/db/database.js
> +		if (length !== undefined && length !== null) {
`if(length)` is enough here

2023-08-03 11:49 UTC, vmutafov commented on components/api-database/src/main/resources/META-INF/dirigible/db/extensions/db.d.ts
> +        setBinaryStream(index: number, inputStream, length?)
We should add the type for the `length` parameter

2023-08-03 11:49 UTC, vmutafov commented on components/api-database/src/main/resources/META-INF/dirigible/db/extensions/db.d.ts
> +        setBinaryStream(index: number, inputStream, length?)
And do we know the `inputStream`'s type?

2023-08-04 12:10 UTC, ThuF approved these changes
+1 Seems good to me.

2023-08-04 12:14 UTC, merged