add mapping for FLOAT8
eclipse/dirigible pull request #2925
Opened 2023-11-06 13:36 UTC by iliyan-velichkov

2023-11-06 13:45 UTC, vmutafov approved these changes

2023-11-06 13:55 UTC, delchev requested changes

2023-11-06 13:55 UTC, delchev commented on components/engine/engine-odata/src/main/java/org/eclipse/dirigible/components/odata/transformers/ODataDatabaseMetadataUtil.java
> +		SQL_TO_ODATA_EDM_TYPES.put("FLOAT8", "Edm.Double");
Please, include also what is missed from STRING_TO_DATABASE_TYPE in DataTypeUtils

2023-11-07 08:43 UTC, iliyan-velichkov commented
moved to new PR https://github.com/eclipse/dirigible/pull/2928/

2023-11-07 08:43 UTC, closed without merging