Update banner + add started and stopped logs
eclipse/dirigible pull request #2996
Opened 2023-11-17 12:25 UTC by iliyan-velichkov

2023-11-22 09:41 UTC, delchev commented
```
2023-11-20 08:52:11.992 [INFO ] [cluster-ClusterId{value='655b021b7cdd2f1160237397', description='null'}-localhost:27017] org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 2, 24]}, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=6102125}
2023-11-20 08:52:12.007 [INFO ] [main] o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8080"]
2023-11-20 08:52:12.016 [INFO ] [main] o.s.b.w.e.tomcat.TomcatWebServer - Tomcat started on port(s): 8080 (http) with context path ''
2023-11-20 08:52:12.017 [INFO ] [main] o.s.m.s.b.SimpleBrokerMessageHandler - Starting...
2023-11-20 08:52:12.017 [INFO ] [main] o.s.m.s.b.SimpleBrokerMessageHandler - BrokerAvailabilityEvent[available=true, SimpleBrokerMessageHandler [org.springframework.messaging.simp.broker.DefaultSubscriptionRegistry@17d25e1d]]
2023-11-20 08:52:12.017 [INFO ] [main] o.s.m.s.b.SimpleBrokerMessageHandler - Started.
2023-11-20 08:52:12.102 [INFO ] [main] o.a.c.i.engine.AbstractCamelContext - Apache Camel 3.21.2 (camel-1) is starting
2023-11-20 08:52:12.109 [INFO ] [main] o.a.c.i.engine.AbstractCamelContext - Routes startup (started:0)
2023-11-20 08:52:12.109 [INFO ] [main] o.a.c.i.engine.AbstractCamelContext - Apache Camel 3.21.2 (camel-1) started in 138ms (build:70ms init:61ms start:7ms)
2023-11-20 08:52:12.114 [INFO ] [main] o.e.dirigible.DirigibleApplication - Started DirigibleApplication in 12.122 seconds (JVM running for 12.532)
2023-11-20 08:52:12.154 [INFO ] [main] o.e.dirigible.DirigibleApplication - 
█████ █████ █████ █████ █████ █████ █████ █████ █████ █████ █████ █████ █████ █████ █████ █████ █████ █████ █████ █████ █████ 
2023-11-20 08:52:12.309 [DEBUG] [main] o.e.d.c.i.s.SynchronizationWatcher - Initializing the Registry file watcher...
2023-11-20 08:52:12.314 [DEBUG] [main] o.e.d.c.i.s.SynchronizationWatcher - Done initializing the Registry file watcher.
2023-11-20 08:52:16.997 [DEBUG] [main] o.e.d.c.i.s.SynchronizationProcessor - Processing synchronizers started...
2023-11-20 08:52:16.998 [TRACE] [main] o.e.d.c.i.s.SynchronizationProcessor - Collecting files...
2023-11-20 08:52:17.101 [DEBUG] [schedulerFactoryBean_Worker-2] o.e.d.c.i.s.SynchronizationJob - Job SynchronizationJobDetail fired @ Mon Nov 20 08:52:17 EET 2023
2023-11-20 08:52:17.101 [DEBUG] [schedulerFactoryBean_Worker-2] o.e.d.c.i.s.SynchronizationJob - Next job scheduled @ Mon Nov 20 08:52:27 EET 2023
2023-11-20 08:52:17.142 [DEBUG] [pool-1-thread-1] o.e.d.c.i.s.SynchronizationJob - Used memory at the start: +74,236,992    
2023-11-20 08:52:17.142 [DEBUG] [pool-1-thread-1] o.e.d.c.i.s.SynchronizationJobService - Synchronization started...
2023-11-20 08:52:17.585 [DEBUG] [main] o.e.d.c.i.s.SynchronizationProcessor - Collecting files done. 20 known types of definitions collected - [extensionpoint, extension, role, access, job, listener, expose, openapi, websocket, datasource, schema, table, view, entity, camel, bpmn, odata, csvim, confluence, markdown].
2023-11-20 08:52:17.585 [TRACE] [main] o.e.d.c.i.s.SynchronizationProcessor - Loading definitions...
2023-11-20 08:52:17.693 [ERROR] [main] o.e.d.c.i.s.SynchronizationProcessor - Attempt to generate an artefact key by type=[extensionpoint], location=[/template-application-ui-angular/ui/launchpad/perspective.extensionpoint], name=[null]
```

just a line should be enough I thing, no need to be too verbose

2023-11-22 09:43 UTC, delchev requested changes

2023-11-22 09:43 UTC, delchev commented on build/application/src/main/resources/banner.txt
> +░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
no need of a logo

2023-11-22 11:52 UTC, iliyan-velichkov commented on build/application/src/main/resources/banner.txt
> +░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
done

2023-11-23 14:38 UTC, delchev approved these changes

2023-11-23 14:38 UTC, merged