Fix SystemDB datasource from configuration properties
eclipse/dirigible pull request #3262
Opened 2024-01-19 14:00 UTC by entrery

2024-01-19 14:05 UTC, entrery commented
@delchev @vmutafov @ThuF please review this small fix

2024-01-19 14:07 UTC, delchev requested changes

2024-01-19 14:07 UTC, delchev commented on components/core/core-database/src/main/java/org/eclipse/dirigible/components/database/DataSourceSystemConfig.java
> +        dataSourceProperties.setDriverClassName(Configuration.get("DIRIGIBLE_DATASOURCE_SYSTEM_DRIVER", "org.h2.Driver"));
Let's use prefix DIRIGIBLE_DATABASE_*
and add documentation here:
https://www.dirigible.io/help/setup/setup-environment-variables/
and add definition here:
https://github.com/eclipse/dirigible/blob/abadf3a1259f5c4b4e08983d0913a735bb45644d/modules/commons/commons-config/src/main/java/org/eclipse/dirigible/commons/config/Configuration.java#L504

2024-01-26 04:34 UTC, iliyan-velichkov commented on components/core/core-database/src/main/java/org/eclipse/dirigible/components/database/DataSourceSystemConfig.java
> +        dataSourceProperties.setPassword(Configuration.get("DIRIGIBLE_DATABASE_SYSTEM_PASSWORD", ""));
you can add the constants [here](https://github.com/eclipse/dirigible/blob/master/modules/commons/commons-config/src/main/java/org/eclipse/dirigible/commons/config/Configuration.java#L44) as well

2024-01-26 04:35 UTC, iliyan-velichkov approved these changes

2024-01-26 13:35 UTC, delchev approved these changes

2024-01-26 13:35 UTC, merged

2024-01-30 09:52 UTC, iliyan-velichkov commented
@delchev note that for Default DS we use [DIRIGIBLE_DATASOURCE_DEFAULT.*](https://github.com/search?q=repo%3Aeclipse%2Fdirigible+DIRIGIBLE_DATASOURCE_DEFAULT&type=code)