Introduce Cache Api
eclipse/dirigible pull request #3593
Opened 2024-03-15 12:51 UTC by MinaDoncheva

### What does this PR do?

### What issues does this PR fix or reference?

#### Release Notes

#### Documentation

2024-03-15 14:11 UTC, ThuF requested changes

2024-03-15 14:11 UTC, ThuF commented on components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/cache/caches.ts
> +    public static get(key: string): string | undefined {
I think the return type should be `any | undefined` instead of `string | undefined`, as the `get()` method in the `CacheFacade` returns `Object`.

2024-03-15 14:11 UTC, ThuF commented on components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/cache/caches.ts
> +const Cache = Java.type("org.eclipse.dirigible.components.api.cache.CacheFacade");
Either all methods in the `CacheFacade` should be `static` (in order to be used in the JS/TS like this `Cache.contains()`), or this should be changed to:

```ts
const CacheFacade = Java.type("org.eclipse.dirigible.components.api.cache.CacheFacade");
const cache = new CacheFacade();

export class Cache {

    public static contains(key: string): boolean {
        return cache.contains(key);
    }
...
```

2024-03-15 14:11 UTC, ThuF commented on components/api/api-modules-javascript/src/main/resources/META-INF/dirigible/modules/src/cache/caches.ts
> +export class Caches {
I guess `Cache` is better name than `Caches`?

2024-03-15 14:11 UTC, ThuF commented on components/api/api-cache/pom.xml
> +	</dependencies>
Please double-check whether all dependencies are needed

2024-03-15 14:11 UTC, ThuF commented on components/api/api-cache/pom.xml
> +	<artifactId>dirigible-components-api-cache</artifactId>
I think the `dirigible-components-api-cache` module, should be added as dependency in one of those, in order to be included in the executable JAR:
- https://github.com/eclipse/dirigible/blob/master/components/group/group-api/pom.xml
- https://github.com/eclipse/dirigible/blob/master/components/group/group-api-core/pom.xml
- https://github.com/eclipse/dirigible/blob/master/components/group/group-api-core/pom.xml

2024-03-19 13:20 UTC, ThuF approved these changes
+1 Seems good to me.

2024-03-19 15:08 UTC, delchev approved these changes

2024-03-19 15:08 UTC, merged